name: publish-doc

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build-and-publish-doc:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v4
    - uses: actions/configure-pages@v4
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        container: el9
        view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
        run: |
          echo "::group::Install dependencies"
          python3 -m pip install -r doc/requirements.txt
          export PATH=/root/.local/bin:$PATH

          echo -e "::endgroup::\n::group::Build podio"
          cmake -B build . --install-prefix=$(pwd)/install \
                -GNinja -DENABLE_SIO=ON -DENABLE_RNTUPLE=ON \
                -DBUILD_TESTING=OFF \
                -DCMAKE_CXX_STANDARD=17
          cmake --build build --target install
          export PYTHONPATH=$(pwd)/install/python:$PYTHONPATH
          export LD_LIBRARY_PATH=$(pwd)/install/lib*/:$LD_LIBRARY_PATH
          export ROOT_INCLUDE_PATH=$(pwd)/install/include

          echo -e "::endgroup::\n::group::build doc"
          sphinx-build -M html doc doc_output

    - name: Setup Pages
      uses: actions/configure-pages@v4
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: doc_output/html
    - name: Deploy to Github pages
      id: deployment
      uses: actions/deploy-pages@v4
