name: key4hep

on:
  push:
    branches:
    - master
  pull_request:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - release: "sw-nightlies.hsf.org/key4hep"
            RNTUPLE: ON
    steps:
    - uses: actions/checkout@v3
    - uses: cvmfs-contrib/github-action-cvmfs@v3
    - uses: aidasoft/run-lcg-view@v4
      with:
        container: centos7
        view-path: /cvmfs/${{ matrix.release }}
        run: |
          echo "::group::Run CMake"
          mkdir build install
          cd build
          cmake -DENABLE_SIO=ON \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror -Wno-error=deprecated-declarations " \
            -DUSE_EXTERNAL_CATCH2=AUTO \
            -DENABLE_RNTUPLE=${{ matrix.RNTUPLE }} \
            -G Ninja ..
          echo "::endgroup::"
          echo "::group::Build"
          ninja -k0
          echo "::endgroup"
          echo "::group::Run tests"
          ctest --output-on-failure
          echo "::endgroup::"
          echo "::group::Install"
          ninja install
          echo "::endgroup::"

  key4hep-sanitizer-builds:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        sanitizer: [Thread,
                    Address,
                    Undefined]
        compiler: [CXX=g++ CC=gcc,
                    CXX=clang++ CC=clang]
    steps:
      - uses: actions/checkout@v3
      - uses: cvmfs-contrib/github-action-cvmfs@v3
      - uses: aidasoft/run-lcg-view@v4
        with:
          container: centos7
          view-path: /cvmfs/sw-nightlies.hsf.org/key4hep
          run: |
            mkdir build
            cd build
            ${{ matrix.compiler }} \
            cmake -DENABLE_SIO=ON \
            -DCMAKE_INSTALL_PREFIX=../install \
            -DCMAKE_CXX_STANDARD=17 \
            -DCMAKE_CXX_FLAGS=" -fdiagnostics-color=always -Werror -Wno-error=deprecated-declarations " \
            -DUSE_EXTERNAL_CATCH2=AUTO \
            -DENABLE_RNTUPLE=ON \
            -DUSE_SANITIZER=${{ matrix.sanitizer }} \
            -G Ninja ..
            ninja -k0
            ctest --output-on-failure
